RustboroCity_PokemonCenter_1F_Text_184B37:: @ 8184B37
	.string "My Pokémon has a NAIVE nature, and my\n"
	.string "friend's has a JOLLY nature.\p"
	.string "It's fascinating how Pokémon have\n"
	.string "personalities!$"

RustboroCity_PokemonCenter_1F_Text_184BAB:: @ 8184BAB
	.string "Just like people, there are male and\n"
	.string "female Pokémon.\p"
	.string "But no one seems to have any idea how\n"
	.string "they're different.$"

RustboroCity_PokemonCenter_1F_Text_184C19:: @ 8184C19
	.string "The man next door gave me an HM!\p"
	.string "I used it to teach my Pokémon how to\n"
	.string "CUT down skinny trees.$"
