SlateportCity_PokemonCenter_1F_Text_180602:: @ 8180602
	.string "Want a tip for battling?\p"
	.string "I'd say it's raising different kinds\n"
	.string "of Pokémon in a balanced manner.\p"
	.string "It's no good to make just one\n"
	.string "Pokémon strong.\p"
	.string "If it has a type disadvantage, it\n"
	.string "might not stand a chance.$"

SlateportCity_PokemonCenter_1F_Text_1806CB:: @ 81806CB
	.string "I trade Pokémon with my friends.\p"
	.string "If a traded Pokémon is holding an\n"
	.string "item, it makes me twice as happy!$"
