VerdanturfTown_Mart_Text_1781C9:: @ 81781C9
	.string "For any Pokémon match, X SPECIAL\n"
	.string "is crucial.\p"
	.string "It jacks up the power of some moves\n"
	.string "even though it's only for one battle.$"

VerdanturfTown_Mart_Text_178240:: @ 8178240
	.string "They don't sell any items that will let\n"
	.string "you win CONTESTS...\p"
	.string "It means you have to raise Pokémon\n"
	.string "diligently on an everyday basis.$"

VerdanturfTown_Mart_Text_1782C0:: @ 81782C0
	.string "The NEST BALL works better on\n"
	.string "weakened Pokémon.\p"
	.string "VERDANTURF is the only place you can\n"
	.string "buy it.$"
