Text_PictureBookshelf: @ 81C6A69
	.string "There's a set of Pokémon picture books.$"

Text_Bookshelf: @ 81C6A91
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookshelf: @ 81C6AB6
	.string "Pokémon magazines!\n"
	.string "Pokémon PAL...\p"
	.string "Pokémon HANDBOOK...\n"
	.string "ADORABLE Pokémon...$"

Text_Vase: @ 81C6B00
	.string "This vase looks expensive...\n"
	.string "Peered inside...\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan: @ 81C6B41
	.string "It's empty.$"

Text_ShopShelf: @ 81C6B4D
	.string "The shelves brim with all sorts of\n"
	.string "Pokémon merchandise.$"

Text_Blueprint: @ 81C6B85
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
