gText_NurseJoy_Welcome:: @ 81A0A7D
	.string "Hello, and welcome to the Pokémon\n"
	.string "CENTER.\p"
	.string "We restore your tired Pokémon to\n"
	.string "full health.\p"
	.string "Would you like to rest your Pokémon?$"

gText_NurseJoy_WeHopeToSeeYouAgain:: @ 81A0AFA
	.string "We hope to see you again!$"

gText_NurseJoy_ThankYouForWaiting:: @ 81A0B14
	.string "Thank you for waiting.\p"
	.string "We've restored your Pokémon to\n"
	.string "full health.$"

UnknownString_81A0B57: @ 81A0B57
	.string "Welcome to the Pokémon CABLE CLUB\n"
	.string "TRADE CENTER.$"

UnknownString_81A0B87: @ 81A0B87
	.string "Welcome to the Pokémon CABLE CLUB\n"
	.string "COLOSSEUM.$"

UnknownString_81A0BB4: @ 81A0BB4
	.string "Welcome to the Pokémon CABLE CLUB\n"
	.string "TIME CAPSULE.$"
