SlateportCity_Mart_Text_180730:: @ 8180730
	.string "Der MARKT bietet einige interessante\n"
	.string "Merchandising-Artikel an.\p"
	.string "Aber einige Sachen wirst du nur in einem\n"
	.string "Pokémon-SUPERMARKT finden.$"

SlateportCity_Mart_Text_18079D:: @ 818079D
	.string "Ein SUPERBALL eignet sich besser zum\n"
	.string "Fangen von Pokémon als ein POKéBALL.\p"
	.string "Hiermit sollte ich in der Lage sein, das\n"
	.string "begehrte Pokémon zu überlisten.$"
