PacifidlogTown_House3_Text_17940E:: @ 817940E
	.string "Hallo, TRAINER. Würdest du Pokémon\n"
	.string "mit mir tauschen?\p"
	.string "Da ich in FLOSSBRUNN lebe, kann ich nur\n"
	.string "bestimmte Pokémon fangen.\p"
	.string "{STR_VAR_1}? Hast du das Pokémon?\n"
	.string "Ich gebe dir mein {STR_VAR_2} dafür.$"

PacifidlogTown_House3_Text_1794C4:: @ 81794C4
	.string "Wow!\n"
	.string "Das {STR_VAR_1} ist so weich!$"

PacifidlogTown_House3_Text_1794DF:: @ 81794DF
	.string "Das ist kein {STR_VAR_1}.$"

PacifidlogTown_House3_Text_1794ED:: @ 81794ED
	.string "Ich bin ein bisschen enttäuscht.$"

PacifidlogTown_House3_Text_17950A:: @ 817950A
	.string "Seit wir Pokémon getauscht haben, sind\n"
	.string "wir Freunde, nicht wahr?$"

PacifidlogTown_House3_Text_179541:: @ 8179541
	.string "Ist das ein POKéDEX?\p"
	.string "Hast du schon viele verschiedene\n"
	.string "Pokémon getroffen?\p"
	.string "Ich wollte, ich wäre wie du.$"
