SlateportCity_PokemonCenter_1F_Text_180602:: @ 8180602
	.string "Möchtest du einen Tipp?\p"
	.string "Ich sage dir, es ist wichtig, die unter-\n"
	.string "schiedlichsten Pokémon zu trainieren.\p"
	.string "Gleichmäßigkeit ist wichtig. Ein\n"
	.string "einzelnes starkes Pokémon reicht nicht.\p"
	.string "Wenn es vom Typ her Nachteile besitzt,\n"
	.string "kann auch ein sehr starkes Pokémon\l"
	.string "einen Kampf verlieren.$"

SlateportCity_PokemonCenter_1F_Text_1806CB:: @ 81806CB
	.string "Ich tausche mit Freunden Pokémon.\p"
	.string "Und wenn ein getauschtes Pokémon ein\n"
	.string "Item trägt, bin ich umso glücklicher!$"
