gText_NurseJoy_Welcome:: @ 81A0A7D
	.string "Willkommen im Pokémon-CENTER!\p"
	.string "Wir heilen deine Pokémon und\n"
	.string "machen sie wieder fit.\p"
	.string "O.K. Wir benötigen deine Pokémon.$"

gText_NurseJoy_WeHopeToSeeYouAgain:: @ 81A0AFA
	.string "Komm jederzeit wieder vorbei!$"

gText_NurseJoy_ThankYouForWaiting:: @ 81A0B14
	.string "Danke!\p"
	.string "Deine Pokémon sind wieder topfit!$"

UnknownString_81A0B57: @ 81A0B57
	.string "Willkommen im Pokémon KABEL-CLUB-\n"
	.string "HANDELSCENTER.$"

UnknownString_81A0B87: @ 81A0B87
	.string "Willkommen im Pokémon KABEL-CLUB-\n"
	.string "KOLOSSEUM.$"

UnknownString_81A0BB4: @ 81A0BB4
	.string "Willkommen in der Pokémon KABEL-CLUB-\n"
	.string "ZEITKAPSEL.$"
