RustboroCity_PokemonSchool_Text_184321:: @ 8184321
	.string "The blackboard lists status changes\n"
	.string "that may affect Pokémon in battle.$"

RustboroCity_PokemonSchool_Text_184368:: @ 8184368
	.string "Which topic do you want to read?$"

RustboroCity_PokemonSchool_Text_184389:: @ 8184389
	.string "If a Pokémon is poisoned, it will\n"
	.string "steadily lose HP.\p"
	.string "The effects of poison remain after\n"
	.string "a battle.\p"
	.string "A poisoned Pokémon's HP will drop\n"
	.string "while it is traveling.\p"
	.string "Heal a poisoning using an ANTIDOTE.$"

RustboroCity_PokemonSchool_Text_184447:: @ 8184447
	.string "If a Pokémon becomes paralyzed,\n"
	.string "its SPEED drops.\p"
	.string "It may also not be able to move while\n"
	.string "it is in battle.\p"
	.string "Paralysis remains after battle.\n"
	.string "Cure it using a PARLYZ HEAL.$"

RustboroCity_PokemonSchool_Text_1844EC:: @ 81844EC
	.string "If a Pokémon falls asleep, it will be\n"
	.string "unable to attack.\p"
	.string "A Pokémon may wake up on its own,\n"
	.string "but if a battle ends while it is sleeping,\l"
	.string "it will stay asleep.\p"
	.string "Wake it up using an AWAKENING.$"

RustboroCity_PokemonSchool_Text_1845A5:: @ 81845A5
	.string "A burn reduces ATTACK power, and it\n"
	.string "steadily reduces the victim's HP.\p"
	.string "A burn lingers after battle.\n"
	.string "Cure a burn using a BURN HEAL.$"

RustboroCity_PokemonSchool_Text_184627:: @ 8184627
	.string "If a Pokémon is frozen, it becomes\n"
	.string "completely helpless.\p"
	.string "It will remain frozen after battle.\n"
	.string "Thaw it out using an ICE HEAL.$"

RustboroCity_PokemonSchool_Text_1846A2:: @ 81846A2
	.string "Students who don't study get a little\n"
	.string "taste of my QUICK CLAW.\p"
	.string "Whether or not you are a good student \n"
	.string "will be evident from the way you use\l"
	.string "this item.$"

RustboroCity_PokemonSchool_Text_184737:: @ 8184737
	.string "A Pokémon holding the QUICK CLAW will\n"
	.string "occasionally speed up and get to move\l"
	.string "before its opponent.\p"
	.string "There are many other items that are\n"
	.string "meant to be held by Pokémon.\p"
	.string "Just those alone will give you many\n"
	.string "topics to study!$"

RustboroCity_PokemonSchool_Text_18480E:: @ 818480E
	.string "I'm trading Pokémon with my friend\n"
	.string "right now.$"

RustboroCity_PokemonSchool_Text_18483C:: @ 818483C
	.string "I always wanted a SEEDOT, and\n"
	.string "I'm finally getting one!$"

RustboroCity_PokemonSchool_Text_184873:: @ 8184873
	.string "Pokémon can hold items, but they\n"
	.string "don't know what to do with man-made\l"
	.string "items like POTION and ANTIDOTE.$"

RustboroCity_PokemonSchool_Text_1848D8:: @ 81848D8
	.string "You know how some Pokémon moves can\n"
	.string "confuse a Pokémon?\p"
	.string "A confused Pokémon will sometimes\n"
	.string "attack itself without meaning to.\p"
	.string "But once it leaves battle, it will\n"
	.string "return to normal.$"

RustboroCity_PokemonSchool_Text_184988:: @ 8184988
	.string "A Pokémon holding a BERRY will heal\n"
	.string "itself...\p"
	.string "There are many kinds of items that\n"
	.string "Pokémon can hold...\p"
	.string "Boy, it sure is hard taking notes\n"
	.string "down...$"

RustboroCity_PokemonSchool_Text_184A17:: @ 8184A17
	.string "It's this student's notebook...\p"
	.string "Pokémon are to be caught using\n"
	.string "POKé BALLS.\p"
	.string "Up to six Pokémon can accompany\n"
	.string "a TRAINER.\p"
	.string "A TRAINER is someone who catches\n"
	.string "Pokémon, raises them, and battles\l"
	.string "with them.\p"
	.string "A TRAINER's mission is to defeat the\n"
	.string "strong TRAINERS who await challengers\l"
	.string "in Pokémon GYMS.$"
