VerdanturfTown_House_Text_178D11:: @ 8178D11
	.string "Weit von hier, in PRACHTPOLIS CITY,\n"
	.string "findest du die Pokémon LIGA.\p"
	.string "Die TRAINER dort sind alle geradezu\n"
	.string "Furcht erregend talentiert.$"

VerdanturfTown_House_Text_178D8E:: @ 8178D8E
	.string "In der Pokémon LIGA musst du die TOP\n"
	.string "VIER hintereinander besiegen. Das\l"
	.string "sagen die Regeln.\p"
	.string "Wenn du gegen einen dieser TRAINER\n"
	.string "verlierst, musst du die Herausforderung\l"
	.string "von vorne beginnen.$"
